from enum import Enum


class AiThreadTypeEnum(Enum):
    KEYWORD_TRACKING_INSIGHTS = "KEYWORD TRACKING"
    CONTENT_MANAGEMENT_INSIGHTS = "CONTENT MANAGEMENT"
    HASHTAG_TRACKING_INSIGHTS = "HASHTAG TRACKING"
    ACCOUNT_TRACKING_INSIGHTS = "ACCOUNT TRACKING"
    LEAD_TRACKING_INSIGHTS = "LEAD TRACKING"
