from enum import Enum
from typing import Dict
from app.core.helpers.queueenum_helper import QueueEnumTypeHelper


# Enum for azure queues
class QueueEnum(Enum):
    @classmethod
    def create_enums(cls, enum_names: Dict[str, str]):
        QueueEnumTypeHelper.create_queue_type_enums(cls, enum_names)
        return cls


queue_message_type_enums = {
    "NOTIFICATION": "NOTIFICATION",
    "AUTH_NOTIFICATION": "AUTH_NOTIFICATION",
    "JOB_APPLICATION_NOTIFICATION": "JOB_APPLICATION_NOTIFICATION",
    "FEED_NOTIFICATION": "FEED_NOTIFICATION",
    "GROUP_CHAT_NOTIFICATION": "GROUP_CHAT_NOTIFICATION",
    "CHAT_NOTIFICATION": "CHAT_NOTIFICATION",
    "REVIEW_NOTIFICATION": "REVIEW_NOTIFICATION",
    "ADMIN_NOTIFICATION": "ADMIN_NOTIFICATION",
    "JOB_NOTIFICATION": "JOB_NOTIFICATION",
    "JOB_BOOKING_NOTIFICATION": "JOB_BOOKING_NOTIFICATION",
    "CREATIVE_PROFILE_NOTIFICATION": "CREATIVE_PROFILE_NOTIFICATION",
    "USER_NOTIFICATION": "USER_NOTIFICATION",
    "POST_NOTIFICATION": "POST_NOTIFICATION",
    "TRACKER_NOTIFICATION": "TRACKER_NOTIFICATION",
    "SUBSCRIPTION_NOTIFICATION": "SUBSCRIPTION_NOTIFICATION",
    "SUPPORT_NOTIFICATION": "SUPPORT_NOTIFICATION",
    "REPORT_NOTIFICATION": "REPORT_NOTIFICATION",
    "AUDIT_LOG": "AUDIT_LOG",
    "EXCEPTION_LOG": "EXCEPTION_LOG",
    "KEYWORD_TRACKING_NOTIFICATION": "KEYWORD_TRACKING_NOTIFICATION",
    "HASHTAG_TRACKING_NOTIFICATION": "HASHTAG_TRACKING_NOTIFICATION",
    "CONTENT_MANAGEMENT_NOTIFICATION": "CONTENT_MANAGEMENT_NOTIFICATION",
    "ACCOUNT_TRACKING_NOTIFICATION": "ACCOUNT_TRACKING_NOTIFICATION",
    "ALERT_NOTIFICATION": "ALERT_NOTIFICATION",
    "FILE_GENERATION": "FILE_GENERATION",
    "LEAD_TRACKING_NOTIFICATION": "LEAD_TRACKING_NOTIFICATION",
    "LEAD_PROCESSING_QUEUE": "LEAD_PROCESSING_QUEUE",
    "LEAD_GENERATION_QUEUE": "lead_generation_queue",
    "NEW_SUBSCRIPTION_QUEUE": "NEW_SUBSCRIPTION_QUEUE",
    "FILE_IMPORT_QUEUE": "FILE_IMPORT_QUEUE",
    "LEAD_MANAGEMENT_QUEUE": "LEAD_MANAGEMENT_QUEUE",
    "LEAD_FORM_NOTIFICATION_QUEUE": "LEAD_FORM_NOTIFICATION_QUEUE",
    "LAZARUS_MONITORING_QUEUE": "LAZARUS_MONITORING_QUEUE",
}

QueueEnum.create_enums(queue_message_type_enums)
